service: resize-image

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  architecture: arm64
  region: ap-southeast-1
  logRetentionInDays: ${self:custom.logRetentionInDays.${sls:stage}, 7}
  deploymentBucket:
    name: serverless-base-dev-bucket
  stackTags:
    CreatedBy: "harithzainudin7@gmail.com"
    ProjectName: "Resize Image"
  environment:
    IMAGE_BUCKET_NAME: ${self:service}-${sls:stage}-bucket
    LOG_LEVEL: ${self:custom.logLevel.${sls:stage}, "info"}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "lambda:*"
          Resource: "*"
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "*"

functions:
  - ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/s3.yml)}

plugins:
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

custom:
  # accepted value & level
  # error: 0, warn: 1, info: 2, http: 3, verbose: 4, debug: 5, silly: 6
  logLevel:
    dev: "debug"
    staging: "debug"
    prod: "info"
    uat: "info"
  logRetentionInDays:
    dev: 7
    staging: 7
    prod: 30
    uat: 30
  includeDependencies:
    enableCaching: true
  prune:
    automatic: true
    number: 2

package:
  individually: true
